### ISSUE TITLE
[input[type=number]下能输入e、+、-的解决方案_王一诺Eno的博客-CSDN博客_input type=number 可以输入e

### ISSUE THREAD

**Issue by HenryTSZ** [HenryTSZ/hello-world#41]
![](https://csdnimg.cn/release/blogv2/dist/pc/img/original.png)

版权声明：本文为博主原创文章，遵循 [CC 4.0 BY-SA](http://creativecommons.org/licenses/by-sa/4.0/) 版权协议，转载请附上原文出处链接和本声明。

> 在我们开发过程中，难免遇到这样的需求，需要一个输入框，并且只能输入数字，不能输入其他任何字符，这时候各种正则[校验](https://so.csdn.net/so/search?q=%E6%A0%A1%E9%AA%8C&spm=1001.2101.3001.7020)替换真的是苦不堪言~ 有时候弄得焦头烂额还要被嘲讽 le se … 接下来给大家介绍个神奇的解决方案，走过路过的朋友，有钱的捧个钱场，没钱的捧个人场，点个赞什么的我最喜欢啦；废话说多了，下边请看:

### 输入框 input\[type=number]

首先为何输入框 input\[type=number]能输入 e 呢？ 究竟这个 e 是何方神圣，查阅资料得知，原来 e = 2.71828…

解决:  
在 inpu[原生事件](https://www.runoob.com/jsref/event-onkeypress.html)中把非数字的按键过滤掉，具体操作如下:

```javascript
onKeypress="return (/[\d]/.test(String.fromCharCode(event.keyCode)))" 


 <input v-model="goPage"
   onKeypress="return (/[\d]/.test(String.fromCharCode(event.keyCode)))" 
   :max="9999999" type="number" placeholder="请输入"></input>
        

```

惊不惊喜？意不意外？是不是解决啦 ^ \_ ^

作者就是喜欢买一送一！  
输入框有自带的上下箭头，即 input\[type=number]实际上为步距输入框也就是计数器… 会有自带的样式，顺带下面附上解决方案…

### CSS 去默认样式

```css
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
input[type="number"]{
  -moz-appearance: textfield;
}
// vue的scope下
/deep/ input::-webkit-outer-spin-button,
/deep/ input::-webkit-inner-spin-button {
  -webkit-appearance: none;
}
/deep/ input[type="number"]{
  -moz-appearance: textfield;
}

```

> 总结：没有什么坑解决不了滴，如果对你有帮助，请点个关注或者喜欢喔

> 楼主博客[安静 Eno](https://wlove-c.github.io/)

> 楼主[github](https://github.com/wLove-c) 
>  [https://blog.csdn.net/weixin_40755688/article/details/95794638](https://blog.csdn.net/weixin_40755688/article/details/95794638)
